from rag import retrieving_documents
import ollama

client = ollama.Client()
model = 'llama3.2'

def policy_bot(user_query, file_path):
    retireved_document = retrieving_documents(user_query, file_path)
    prompt_template = """Hi, your name is Hr_bot generated by Tushar khitoliya : Give me the {query} from HR poclicy in {similar_query}. No irrelevant info. 
            Provide me the exact information in words only. or higlight the relevant information 
            Please provide the answer in a Bulletin Point by focusing on the main topics to cover! 
            after proving the information you can ask me for the next query ?."""
    prompt = prompt_template.format(query = user_query, similar_query = retireved_document)
    output = client.generate(model = model, prompt = prompt).response
    
    if output:
        print("Documents retrieved successfully!")
        print("Retrieved Document:")
        return output
    else: 
        print("No relevant documents found for your query.")
